config/routes.rb
Rails.application.routes.draw do
  resources :open_plans
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
  
  resources :plans
  
  resources :open_plans, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :money, presence: true, length: { maximum: 255 }
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  
  has_many :plans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :edit, :update]
  
  def index
    @plans = Plan.order(created_at: :desc).all
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def new
    @plan = Plan.new
  end
  
  def create
    
    @plan = current_user.plans.build(plan_params)
    if @plan.save
      flash[:success] = 'プランを登録しました。'
      redirect_to @plan
    else
      @plans = current_user.plans.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'プランの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @plan = Plan.find(params[:id])
  end
  
  def update
    @plan = Plan.find(params[:id])

    if @plan.update(plan_params)
      flash[:success] = 'プラン は正常に更新されました'
      redirect_to @plan
    else
      flash.now[:danger] = 'プラン は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    flash[:success] = 'プランを削除しました。'
    redirect_to user_path(current_user)
  end
  
  def plan_params
    params.require(:plan).permit(:title, :address, :content, :money, :status, :friendly_id)
  end
  def correct_user
    @plan = current_user.plans.find_by(id: params[:id])
    unless @plan
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @plan = current_user.plans.build  # form_for 用
      @plans = current_user.plans.order('created_at DESC').page(params[:page])
      
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @plans = @user.plans.order('created_at DESC').page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def correct_user
    @user = current_user.plans.find_by(id: params[:id])
    unless @user
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">過ごし方</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'プラン登録', new_plan_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'ユーザー登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>過ごし方</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/plans/_plans.html.erb
<ul class="media-list">
  <% plans.each do |plan| %>
    <% if current_user == plan.user %>
      <% user = plan.user %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= link_to user.name, user_path(user) %>
          </div>
          <div>
            <p><%= link_to plan.title, plan %></p>
          </div>
          <div>
            <% if current_user == plan.user %>
              <%= link_to "Delete", plan, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            <% end %>
          </div>
        </div>
      </li>
    <% else %>
      <% user = plan.user %>
      <% if plan.status == 1 %>
        <li class="media">
          <div class="media-left">
            <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt="">
          </div>
          <div class="media-body">
            <div>
              <%= link_to user.name, user_path(user) %>
            </div>
            <div>
              <p><%= link_to plan.title, plan %></p>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  <% end %>
  <%= paginate plans %>
</ul>

app/views/plans/destroy.html.erb
<h1>Plans#destroy</h1>
<p>Find me in app/views/plans/destroy.html.erb</p>

app/views/plans/edit.html.erb
<h1>id: <%= @plan.id %> のメッセージ編集ページ</h1>

<%= form_for(@plan) do |f| %>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address, '住所' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, '内容' %>
    <%= f.text_area :content, size: "100x10", class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :money, '金額' %>
    <%= f.text_area :money, size: "100x4", class: 'form-control' %>
  </div>

  <%= f.submit '修正', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to '一覧に戻る', plans_path %>

app/views/plans/index.html.erb
<h1>プラン一覧</h1>

<ul class="list-group">
  <% @plans.each do |plan| %>
    <li class="list-group-item"><%= link_to plan.title, plan %></li>
  <% end %>
</ul>

<%= link_to '新規プランの投稿', new_plan_path %>

app/views/plans/new.html.erb
<h1>プラン新規作成ページ</h1>

<div class="panel panel-default col-xs-8 col-xs-offset-2 panel-body">
  
<%= form_for(@plan) do |f| %>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address, '住所' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, '内容' %>
    <%= f.text_area :content, size: "100x10", class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :money, '金額' %>
    <%= f.text_area :money, size: "100x4", class: 'form-control' %>
  </div>

  <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
<% end %>
</div>
<div class="col-xs-8 col-xs-offset-2">
  <%= link_to '一覧に戻る', plans_path %>

</div>

app/views/plans/show.html.erb
<h1>プラン【<%= @plan.title %>】の詳細ページ</h1>

<div class="panel panel-default col-xs-8 col-xs-offset-2 panel-body">
  <table class="table">
    <tr>
      <th>タイトル</th>
      <td><%= @plan.title %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @plan.address %></td>
    </tr>
    <tr>
      <th>内容</th>
      <td><%= @plan.content %></td>
    </tr>
    <tr>
      <th>金額</th>
      <td><%= @plan.money %></td>
    </tr>
  </table>
</div>
<% if current_user == @plan.user %>
  <div class="col-xs-8 col-xs-offset-2">
    <%= link_to 'マイページへ', user_path(current_user) %>
    <%= link_to 'このプランを編集する', edit_plan_path(@plan) %>
    <%= link_to 'このプランを削除する', @plan, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
  </div>
  <div class="col-xs-8 col-xs-offset-2">
  <% if @plan.status == 0 %>
    <%= form_for(@plan) do |f| %>
      <%= hidden_field_tag 'plan[status]' , '1' %>
      <%= submit_tag '公開', class: 'btn btn-success' %>
    <% end %>
  <% else %>
    <%= form_for(@plan) do |f| %>
      <%= hidden_field_tag 'plan[status]' , '0' %>
      <%= submit_tag '非公開', class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  </div>
<% end %>

app/views/plans/update.html.erb
<h1>Plans#update</h1>
<p>Find me in app/views/plans/update.html.erb</p>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>私の過ごし方プラン</h1>
      <%= link_to 'プラン登録', new_plan_path, class: 'btn btn-lg btn-primary' %>
    </div>
    
  </div>
  <ul class="list-group">
      <% @plans.each do |plan| %>
      
        <% if current_user == plan.user %>
      <% user = plan.user %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= link_to user.name, user_path(user) %>
          </div>
          <div>
            <p><%= link_to plan.title, plan %></p>
          </div>
          <div>
            <% if current_user == plan.user %>
              <%= link_to "Delete", plan, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            <% end %>
          </div>
        </div>
      </li>
    <% else %>
      <% user = plan.user %>
      <% if plan.status == 1 %>
        <li class="media">
          <div class="media-left">
            <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt="">
          </div>
          <div class="media-body">
            <div>
              <%= link_to user.name, user_path(user) %>
            </div>
            <div>
              <p><%= link_to plan.title, plan %></p>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
      <% end %>
      
  </ul>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>私の過ごし方プラン</h1>
      <%= link_to 'ユーザー登録はこちらから！', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4 col-xs-offset-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
      <div class="panel-heading">
        <h3 class="panel-title text-center"><%= @user.name %></h3>
      </div>
    </div>
  </aside>
  <div class="col-xs-12">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>マイプラン<% end %></li>
      <li><a href="#">フォロー</a></li>
      <li><a href="#">フォロワー</a></li>
      <li><a href="#">お気に入りプラン</a></li>
    </ul>
    <%= render 'plans/plans', plans: @plans %>
  </div>
</div>